/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicNotifyLeadRouteImport } from './routes/api.public.notify-lead'
import { Route as AuthenticatedDashboardTradeRouteImport } from './routes/_authenticated.dashboard.trade'
import { Route as AuthenticatedDashboardHomeownerRouteImport } from './routes/_authenticated.dashboard.homeowner'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicNotifyLeadRoute = ApiPublicNotifyLeadRouteImport.update({
  id: '/api/public/notify-lead',
  path: '/api/public/notify-lead',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardTradeRoute =
  AuthenticatedDashboardTradeRouteImport.update({
    id: '/dashboard/trade',
    path: '/dashboard/trade',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardHomeownerRoute =
  AuthenticatedDashboardHomeownerRouteImport.update({
    id: '/dashboard/homeowner',
    path: '/dashboard/homeowner',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/dashboard/homeowner': typeof AuthenticatedDashboardHomeownerRoute
  '/dashboard/trade': typeof AuthenticatedDashboardTradeRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/dashboard/homeowner': typeof AuthenticatedDashboardHomeownerRoute
  '/dashboard/trade': typeof AuthenticatedDashboardTradeRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/search': typeof SearchRoute
  '/signup': typeof SignupRoute
  '/_authenticated/dashboard/homeowner': typeof AuthenticatedDashboardHomeownerRoute
  '/_authenticated/dashboard/trade': typeof AuthenticatedDashboardTradeRoute
  '/api/public/notify-lead': typeof ApiPublicNotifyLeadRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/dashboard/homeowner'
    | '/dashboard/trade'
    | '/api/public/notify-lead'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/dashboard/homeowner'
    | '/dashboard/trade'
    | '/api/public/notify-lead'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/search'
    | '/signup'
    | '/_authenticated/dashboard/homeowner'
    | '/_authenticated/dashboard/trade'
    | '/api/public/notify-lead'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SearchRoute: typeof SearchRoute
  SignupRoute: typeof SignupRoute
  ApiPublicNotifyLeadRoute: typeof ApiPublicNotifyLeadRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/notify-lead': {
      id: '/api/public/notify-lead'
      path: '/api/public/notify-lead'
      fullPath: '/api/public/notify-lead'
      preLoaderRoute: typeof ApiPublicNotifyLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard/trade': {
      id: '/_authenticated/dashboard/trade'
      path: '/dashboard/trade'
      fullPath: '/dashboard/trade'
      preLoaderRoute: typeof AuthenticatedDashboardTradeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/homeowner': {
      id: '/_authenticated/dashboard/homeowner'
      path: '/dashboard/homeowner'
      fullPath: '/dashboard/homeowner'
      preLoaderRoute: typeof AuthenticatedDashboardHomeownerRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardHomeownerRoute: typeof AuthenticatedDashboardHomeownerRoute
  AuthenticatedDashboardTradeRoute: typeof AuthenticatedDashboardTradeRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardHomeownerRoute: AuthenticatedDashboardHomeownerRoute,
  AuthenticatedDashboardTradeRoute: AuthenticatedDashboardTradeRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SearchRoute: SearchRoute,
  SignupRoute: SignupRoute,
  ApiPublicNotifyLeadRoute: ApiPublicNotifyLeadRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
